yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  rich-markdown-editor@*:
      peerDependencies:
        react: "*"
        react-dom: "*"
        styled-components: "*"
  styled-components@*:
      peerDependencies:
        react-is: "*"
        markdown-it: "*"