yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  rich-markdown-editor@*:
    peerDependencies:
      prop-types: "*"
  "@ant-design/icons@*":
    peerDependencies:
      react-dom: "*"
  styled-components@*:
    peerDependencies:
      markdown-it: "*"
