yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@ant-design/icons@*":
    peerDependencies:
      react-dom: "*"
  rich-markdown-editor@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
      styled-components: "*"
  styled-components@*:
    peerDependencies:
      react-is: "*"
      markdown-it: "*"
