version: "3.5"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - api_host=
        - api_prefix=
        - path_prefix=
    image: __IMAGE_NAME_NGINX__:__COMMIT_TAG__